feat(BUX-420): go version and workflows update + config change for pulse deployment
bitcoin-sv/block-headers-service pull request #165
Opened 2024-01-03 14:46 UTC by kuba-4chain

# Pull Request Checklist

- [x] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/pulse/blob/main/.github/CODE_STANDARDS.md)
- [x] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/pulse/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [x] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [x] 💾 PR was issued based on the Github or Jira issue.

2024-01-03 16:03 UTC, arkadiuszos4chain submitted a review, later dismissed

2024-01-04 06:34 UTC, dorzepowski approved these changes

2024-01-04 07:00 UTC, dorzepowski requested changes
There is Go version mentioned in README 😞 
I would suggest to remove it from README, so we don't need to maintain it.

2024-01-04 07:45 UTC, Nazarii-4chain submitted a review, later dismissed

2024-01-04 11:56 UTC, dorzepowski approved these changes

2024-01-04 11:57 UTC, merged